[package]
name = "reversi"
version = "1.0.0"
authors = ["Kaito Sugimoto <7X.rusk@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
rand = "0.6"
regex = "1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false 
features = ["precommit-hook", "run-cargo-fmt"]